use CC;

DROP TABLE IF EXISTS Product;
CREATE TABLE Product (name VARCHAR(255), Made_by VARCHAR(255), PID INT NOT NULL AUTO_INCREMENT, insert_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (PID));

DROP TABLE IF EXISTS Ranked;
CREATE TABLE Ranked (prank INT NOT NULL, pname VARCHAR(255), dname VARCHAR(255), insert_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL);

DROP TABLE IF EXISTS Department;
CREATE TABLE Department (name VARCHAR(255));

DROP TABLE IF EXISTS Brand;
CREATE TABLE Brand (name VARCHAR(255), Made_by VARCHAR(255), PID INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (PID));

DROP TABLE IF EXISTS Company;
CREATE TABLE Company (name VARCHAR(255), CID INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (CID));

DROP TABLE IF EXISTS PermIndex;
CREATE TABLE PermIndex (last_scraped_section VARCHAR(255));